env:
  browser: true
  es6: true
  jasmine: true
  mocha: true
  amd: true
plugins:
  - angular
  - svelte3
  - prettier
extends:
  - prettier
  # - standard
parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: 2020
  sourceType: module
ignorePatterns:
  - "coverage/"
  - "node_modules/"
  - "webpack*.*"
rules:
  quotes: 0
  semi: 0
  comma-dangle: 0
  no-return-assign: 0
  no-useless-escape: 0
  space-before-blocks: 0
  padded-blocks: 0
  import/no-webpack-loader-syntax: 0
  space-before-function-paren:
    - error
    - anonymous: never
      named: never
      asyncArrow: always

#   angular/di:
#     - 2
#     - "$inject"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  "angular": false
  "chai": false
  "describe": false
  "it": false
  "before": false
  "beforeEach": false
  "after": false
  "afterEach": false
  "inject": false
  "_": false
  "$": false
  "jQuery": false
