import angular from 'angular'

export default angular.module("packet", [
	'ngAnimate',
	'ngCookies',
	'ngStorage',
	'ngSanitize',
	'ngTouch',
	'ui.router',
	'ui.bootstrap',
	'angularMoment',
	'oc.lazyLoad',
	'swipe',
	'ngBootstrap',
	'truncate',
	'uiSwitch',
	'toaster',
	'ngAside',
	'vAccordion',
	'vButton',
	'oitozero.ngSweetAlert',
	'angular-notification-icons',
	'angular-ladda',
	'angularAwesomeSlider',
	'slickCarousel',
	'cfp.loadingBar',
	'ncy-angular-breadcrumb',
	'duScroll',
	'pascalprecht.translate',
	'FBAngular'
]).name
