import './vendor.scss'
import 'ti-icons/css/themify-icons.css'
import 'perfect-scrollbar/css/perfect-scrollbar.css'
import 'toastr/build/toastr.css'
import 'sweetalert/lib/sweet-alert.css'
// import 'Select2/select2.css'
// import 'select2-bootstrap-css/select2-bootstrap.css'
import 'angular-loading-bar/build/loading-bar.css'
import 'animate.css/animate.css'
import 'v-button/dist/v-button.css'
import 'ladda/dist/ladda-themeless.min.css'
import 'angular-xeditable/dist/css/xeditable.css'
// OLD?
import 'eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css' // change to scss
import '../../components/jquery-file-upload-angular/css/jquery.fileupload.css'
