export default [ // Taken from https://gist.github.com/unceus/6501985
  { id: 1, name: 'Åland Islands', code: 'AX' },
  { id: 2, name: 'Austria', code: 'AT' },
  { id: 3, name: 'Azerbaijan', code: 'AZ' },
  { id: 4, name: 'Brazil', code: 'BR' },
  { id: 5, name: 'British Indian Ocean Territory', code: 'IO' },
  { id: 6, name: 'Brunei Darussalam', code: 'BN' },
  { id: 7, name: 'Bulgaria', code: 'BG' },
  { id: 8, name: 'Canada', code: 'CA' },
  { id: 9, name: 'Cape Verde', code: 'CV' },
  { id: 10, name: 'Cayman Islands', code: 'KY' },
  { id: 11, name: 'Christmas Island', code: 'CX' },
  { id: 12, name: 'Cocos (Keeling) Islands', code: 'CC' },
  { id: 13, name: 'Colombia', code: 'CO' },
  { id: 14, name: 'Denmark', code: 'DK' },
  { id: 15, name: 'Djibouti', code: 'DJ' },
  { id: 16, name: 'Dominica', code: 'DM' },
  { id: 17, name: 'Dominican Republic', code: 'DO' },
  { id: 18, name: 'Mali', code: 'ML' },
  { id: 19, name: 'Malta', code: 'MT' },
  { id: 20, name: 'Netherlands', code: 'NL' },
  { id: 21, name: 'New Caledonia', code: 'NC' },
  { id: 22, name: 'Pakistan', code: 'PK' },
  { id: 23, name: 'Palau', code: 'PW' },
  { id: 24, name: 'Palestinian Territory, Occupied', code: 'PS' },
  { id: 25, name: 'Panama', code: 'PA' },
  { id: 26, name: 'Papua New Guinea', code: 'PG' },
  { id: 27, name: 'Saint Helena', code: 'SH' },
  { id: 28, name: 'Saint Kitts and Nevis', code: 'KN' },
  { id: 29, name: 'Swaziland', code: 'SZ' },
  { id: 30, name: 'Sweden', code: 'SE' },
  { id: 31, name: 'Switzerland', code: 'CH' },
  { id: 32, name: 'Uganda', code: 'UG' },
  { id: 33, name: 'Ukraine', code: 'UA' },
  { id: 34, name: 'United Emirates', code: 'AE' },
  { id: 35, name: 'United Kingdom', code: 'GB' },
  { id: 36, name: 'United States', code: 'US' },
  { id: 37, name: 'Uruguay', code: 'UY' },
  { id: 38, name: 'Uzbekistan', code: 'UZ' },
  { id: 39, name: 'Vanuatu', code: 'VU' },
  { id: 40, name: 'Yemen', code: 'YE' },
  { id: 41, name: 'Zambia', code: 'ZM' },
  { id: 42, name: 'Zimbabwe', code: 'ZW' }
]
