#!/bin/bash

# enable nodejs and switch to the latest version
source ~/.nvm/nvm.sh
nvm use 0.10.25

# install all required components
npm install
bower install

# start virtual frame buffer
./script/xvfb start

# run the specs
grunt test --browsers=PhantomJS,Chrome
# capture the results
RESULT=$?

# stop virtual frame buffer
./script/xvfb stop

# output the test results
exit $RESULT
