#!/bin/bash

# update selenium
./node_modules/protractor/bin/webdriver-manager update

. ./script/lib/server

startServer

grunt build:dev
grunt configureProxies connect:integration watch &
PID=$!

function isRunning() {
  nc -vz localhost 9000 &> /dev/null
}

echo -n "Waiting for the frontend server."
while ! isRunning; do
  echo -n "."
  sleep 0.1
done

echo -e "\nRunning integration specs."

./node_modules/protractor/bin/protractor ./tests/protractor-conf.coffee
RESULT=$?

stopServer

echo "Killing the frontend server PID=$PID"
kill "$PID"

echo "Done!"
exit $RESULT
