#!/bin/bash

CURRENT_DIR=`pwd`
ANGLE_GRINDER_DIR=$CURRENT_DIR

if [ ! -d "$ANGLE_GRINDER_DIR" ]; then
  echo "Cannot found $ANGLE_GRINDER_DIR"
  exit 1
fi

SKIP_DEPENDENCIES=0

# Read and parse commandline options
while :
do
  case $1 in
    --skip-dependiences | -d)
      SKIP_DEPENDENCIES=$((SKIP_DEPENDENCIES+1))
      shift
      ;;
    *) # no more options
      break
      ;;
   esac
done

# Cleanup the output directory
OUTPUT_DIRECTORY="$CURRENT_DIR/grails/ag-plugin/grails-app/assets/angleGrinder"
if [ ! -d "$OUTPUT_DIRECTORY" ]; then
  echo "Cannot found $OUTPUT_DIRECTORY"
  exit 1
fi

cd "$OUTPUT_DIRECTORY"
git ls-files --others | xargs rm -rf

# Update sources and install all required components
cd $ANGLE_GRINDER_DIR

if [ $SKIP_DEPENDENCIES -eq 0 ]; then
  npm install
  bower install
else
  echo -n "\n=== Skipping dependencies installation ===\n"
fi

# Build the app and copy the output to the right place
echo "Build the app.."
grunt build

echo "Copy the build to the right place.."
cp -R dist/* "$OUTPUT_DIRECTORY"

# Cleanup: do not include demo app in the build
rm "$OUTPUT_DIRECTORY/scripts/exampleApp.min.js"
rm "$OUTPUT_DIRECTORY/scripts/docs.js"
rm "$OUTPUT_DIRECTORY/index.html"
rm "$OUTPUT_DIRECTORY/styles/style.min.css"
rm "$OUTPUT_DIRECTORY/styles/docs.css"

echo "Done!"
exit 0
